#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := circle.cpp line.cpp rectangle.cpp window.cpp filled_rectangle.cpp

# header files in this project
HEADERS := circle.hpp line.hpp rectangle.hpp window.hpp filled_rectangle.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
