#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := circle.cpp line.cpp rectangle.cpp vector.cpp window.cpp drawable.cpp ball.cpp wall.cpp victim.cpp

# header files in this project
HEADERS := circle.hpp line.hpp rectangle.hpp vector.hpp window.hpp drawable.hpp ball.hpp wall.hpp victim.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
